### ISSUE TITLE
How the train_set.dt is created ?

### ISSUE THREAD

**Issue by krishna51119** [ilucasgoncalves/AuxFormer#1]
How to create these three sets for training model

**Comment by ilucasgoncalves** [comment]
You can create a dictionary with the parameters ex:
```
dic = {split: {'labels' : lbl_vec, 'audio': aud_vec, 'vision': vis_vec}}

def get_data(dataset, split='train'):
    data = Audiovisual_dataset( dataset, split)
 
    return data

data = get_data(dic, split)
```

and save them in format .dt with torch.save(data, './location/data.dt')


You can also create your own dataloader method and use it with the code. I am going to try to provide a sample of how data looks like here.

**Comment by krishna51119** [comment]
Thank for reply, but from where the code is taking input wave files? and where to use this dictionary?

**Comment by ilucasgoncalves** [comment]
So the features used in this model are 130 LLDs extracted from the wav files using the opensmile toolkit (the code you need can be found here https://github.com/winston-lin-wei-cheng/opensmile-LLDs-extraction), and the visual features are extracted using the VGG-face model (the code you need can be found here: https://www.robots.ox.ac.uk/~albanie/pytorch-models.html).

This data pre-processing is done beforehand. The features are then save in a dictionary format as explained above. Here is a sample file with the format you would want (https://drive.google.com/drive/folders/1LKYb0cA-_RuATk82XksqnQRJ0UEhbIpK?usp=sharing).


Here's a snipped of how you can create these files ( you can also use different methods, I only used this way because this was the way I was saving my partitions).


```  
    from src.dataset import Audiovisual_dataset
    def get_data(dataset, split='train'):
        data = Audiovisual_dataset( dataset, split)
 
        return data


    filesAud = '/media/dataset/audio_lld_features/' 
    filesVid = '/media/dataset/visual_VGG_features/'   
    listed = sorted(os.listdir(filesAud))
    indexes = np.arange(len(listed))

    label_type = 'class'
    num_class = '6-class'
    
    emos = ['H', 'A', 'N', 'D', 'S', 'F']

    np.random.seed(random_seed)
    np.random.shuffle(indexes)

    if label_type == 'class':
        shuffled = [listed[k] for k in indexes]

    filenames = []

    for f in shuffled:
        e = f.replace('.mat','')[9:10]
        if e in emos:
            filenames.append(f)
            


    length = len(train)
    c = 0
    split = 'train'
    namef = tr_name
    aud_vec = []
    vis_vec = []
    lbl_vec = []
        
    for i in range(length):
        for n in range(len(filenames)):
            
            if str(train[i]) in filenames[n]:
                c += 1
                
                vid = (sio.loadmat(filesVid + (filenames[n]).replace('.mat','_aligned.mat'))['Visual_data']).astype(np.float32)
                aud = (sio.loadmat(filesAud + filenames[n])['Audio_data']).astype(np.float32)
                lbl = (class2onehot_4class(filenames[n].replace('.mat','')[9:10])).astype(np.float32)
                
                aud_vec.append(aud)
                vis_vec.append(vid)
                lbl_vec.append([lbl])


    dic = {split: {'labels' : lbl_vec, 'audio': aud_vec, 'vision': vis_vec}}
    data = get_data(dic, split)
    saveto = location + 'filename.dt'
    torch.save(data, saveto)
    print(split + ' is done')`
```

**Comment by krishna51119** [comment]
Thanks again, however still I am not able to retrieve the features properly, maybe I am trying on a different dataset.
Can I get this dataset? 
Also this video features extraction link is not heading to the code. Can you send a modified direct link plz?

As of now, I am trying with your sample data file. It has a folder named data, I wonder if it has no .dt extension files and no train and test paths as required in the main.py file.
Lastly is it a sample file or the complete data file of this Dataset?

I know lots of questions, :)
I want to reuse your methodology on my toy dataset actually.


Can I get your email id, to share the details?

**Comment by krishna51119** [comment]
I tried this assuming the sample data folder is the desired data for train test and val files.


```
train_location = '......../data_sample/archive/data/94441558042160.dt'
test_location = ''......../data_sample/archive/data/94441554966848.dt'
develop_location =''......../data_sample/archive/data/94426292460416.dt'

train_data = torch.load(train_location)
test_data = torch.load(test_location)
develop_data = torch.load(develop_location)

```


But got this error:

```
magic_number = pickle_module.load(f, **pickle_load_args)

UnpicklingError: invalid load key, '\x00'.
```

**Comment by krishna51119** [comment]
> So the features used in this model are 130 LLDs extracted from the wav files using the opensmile toolkit (the code you need can be found here https://github.com/winston-lin-wei-cheng/opensmile-LLDs-extraction), and the visual features are extracted using the VGG-face model (the code you need can be found here: https://www.robots.ox.ac.uk/~albanie/pytorch-models.html).
> 
> This data pre-processing is done beforehand. The features are then save in a dictionary format as explained above. Here is a sample file with the format you would want (https://drive.google.com/drive/folders/1LKYb0cA-_RuATk82XksqnQRJ0UEhbIpK?usp=sharing).
> 
> Here's a snipped of how you can create these files ( you can also use different methods, I only used this way because this was the way I was saving my partitions).
> 
> ```
>     from src.dataset import Audiovisual_dataset
>     def get_data(dataset, split='train'):
>         data = Audiovisual_dataset( dataset, split)
>  
>         return data
> 
> 
>     filesAud = '/media/dataset/audio_lld_features/' 
>     filesVid = '/media/dataset/visual_VGG_features/'   
>     listed = sorted(os.listdir(filesAud))
>     indexes = np.arange(len(listed))
> 
>     label_type = 'class'
>     num_class = '6-class'
>     
>     emos = ['H', 'A', 'N', 'D', 'S', 'F']
> 
>     np.random.seed(random_seed)
>     np.random.shuffle(indexes)
> 
>     if label_type == 'class':
>         shuffled = [listed[k] for k in indexes]
> 
>     filenames = []
> 
>     for f in shuffled:
>         e = f.replace('.mat','')[9:10]
>         if e in emos:
>             filenames.append(f)
>             
> 
> 
>     length = len(train)
>     c = 0
>     split = 'train'
>     namef = tr_name
>     aud_vec = []
>     vis_vec = []
>     lbl_vec = []
>         
>     for i in range(length):
>         for n in range(len(filenames)):
>             
>             if str(train[i]) in filenames[n]:
>                 c += 1
>                 
>                 vid = (sio.loadmat(filesVid + (filenames[n]).replace('.mat','_aligned.mat'))['Visual_data']).astype(np.float32)
>                 aud = (sio.loadmat(filesAud + filenames[n])['Audio_data']).astype(np.float32)
>                 lbl = (class2onehot_4class(filenames[n].replace('.mat','')[9:10])).astype(np.float32)
>                 
>                 aud_vec.append(aud)
>                 vis_vec.append(vid)
>                 lbl_vec.append([lbl])
> 
> 
>     dic = {split: {'labels' : lbl_vec, 'audio': aud_vec, 'vision': vis_vec}}
>     data = get_data(dic, split)
>     saveto = location + 'filename.dt'
>     torch.save(data, saveto)
>     print(split + ' is done')`
> ```

What is train here?
where you are finding the len(train)?

**Comment by ilucasgoncalves** [comment]
sent you an email with further info

**Comment by ilucasgoncalves** [comment]
Update (10/31/2022):
Updated codes for easier implementation of the model and feature extracting. Releasing corpora partitions for experimental evaluations and features to be used. In this update, we are releasing the wav2vec2 features and EMOCA features version. Opensmile and VGG-Face features are being updated for upcoming release.
