### ISSUE TITLE
how to create dictionary of dataset?

### ISSUE THREAD

**Issue by Coding511** [ilucasgoncalves/AuxFormer#2]
I followed your code snippet in the last issue, where you have created the dict; my query is from audio and video mat files, how to create a dictionary?

**Comment by ilucasgoncalves** [comment]
[dataloading_example.zip](https://github.com/ilucasgoncalves/AuxFormer/files/9170497/dataloading_example.zip)

Here´s a more complete code for data loading . You can use this as a base to modify for your needs and create the dictionaries.

**Comment by Coding511** [comment]
@ilucasgoncalves Could you please upload your features here for a better understanding of your work, like others on GitHub friend, it will be more helpful and certainly boost the citation of your work too.

**Comment by ilucasgoncalves** [comment]
thank you for sharing your thoughts! I have uploaded the features and you can find them under the "Features" section on the readme. Just follow the link and it should take you directly to the drive to download the features for CREMA-D

**Comment by ilucasgoncalves** [comment]
thank you for sharing your thoughts! I have uploaded the features and you can find them under the "Features" section on the readme. Just follow the link and it should take you directly to the drive to download the features for CREMA-D

**Comment by Coding511** [comment]
Thnks
Unfortunately, the file size is too big/
Even not working with colab.

My query is, did you extract these features or used them readymade by
others?
If yes, kindly share the feature extraction files, please.

**Comment by Coding511** [comment]
@ilucasgoncalves can you please reply?
Also as CREMA is available freely we can extract these features for this dataset.

But this dataset codec is not in proper format.
If you have extracted please tell, how did you do that?

**Comment by ilucasgoncalves** [comment]
I just re-downloaded the files from their git-hub to verify its current state. Make sure you follow the instructions listed on their GitHub.If you simply clone the repo and unzip the files, it will not work.

Here are the steps:

   1.  have git-lfs installed (https://github.com/git-lfs/git-lfs/wiki/Installation)
   2. clone the repo (git clone https://github.com/CheyneyComputerScience/CREMA-D.git )

this way should work.

for the MSP-IMPROV dataset, please refer to this page for download (https://ecs.utdallas.edu/research/researchlabs/msp-lab/MSP-Improv.html)

**Comment by Coding511** [comment]
> My query is, did you extract these features or used them readymade by others? If yes, kindly share the feature extraction files, please.

@ilucasgoncalves, sir, please answer this. You have got a good team to work there, and thank you so much for this information, But until one can extract those features themselves, this is useless.

Please share the code to extract video features from scratch.
Also, I read this feature file; what is the meaning of that tensor? 

test_data[0]
Out[8]: 
((0,
  tensor([[-2.2399e-01, -1.8674e+00, -1.3782e-01,  ..., -1.2710e+00,
           -8.4656e-01, -3.8156e-01],
          [-2.2399e-01, -1.1699e+00, -1.3782e-01,  ..., -2.0570e+00,
           -1.2794e+00, -6.4788e-01],
          [-2.2399e-01, -6.0474e-01, -1.3782e-01,  ..., -2.1488e+00,
           -7.4363e-01, -7.3310e-02],
          ...,
          [-2.2399e-01, -3.4965e+00, -1.3782e-01,  ...,  5.5048e-04,
            6.0829e-05,  2.0695e-04],
          [-2.2399e-01, -3.4965e+00, -1.3782e-01,  ...,  5.5048e-04,
            6.0829e-05,  2.0695e-04],
          [-2.2399e-01, -3.4965e+00, -1.3782e-01,  ...,  5.5048e-04,
            6.0829e-05,  2.0695e-04]])),
 tensor([[0., 1., 0., 0., 0., 0.]]))
