### ISSUE TITLE
Is there any paper to compare CREMA results?

### ISSUE THREAD

**Issue by Coding511** [ilucasgoncalves/AuxFormer#3]
Hi
can any one, including the author refer to any paper where these results for CREMA can be compared?

**Comment by ilucasgoncalves** [comment]
All the models and results on the paper were re-run again with same features/datasets/partitions for fair comparison. So you can just compare the results by re-running the experiments on others' models (cited on paper). 


Please note an update on the code.
Update (10/31/2022):
Updated codes for easier implementation of the model and feature extracting. Releasing corpora partitions for experimental evaluations and features to be used. In this update, we are releasing the wav2vec2 features and EMOCA features version. Opensmile and VGG-Face features are being updated for upcoming release.
