### ISSUE TITLE
Where is the "AuxFormer/pre-processing/crema_auds.py"?

### ISSUE THREAD

**Issue by Weah123** [ilucasgoncalves/AuxFormer#5]
Where is the "AuxFormer/pre-processing/crema_auds.py"?

**Comment by ilucasgoncalves** [comment]
@Weah123  It seems I had missed uploading this file before.
Please check again: [AuxFormer/pre-processing/crema_auds.py](https://github.com/ilucasgoncalves/AuxFormer/tree/main/pre-processing)
