### ISSUE TITLE
How to preprocess the CREMA-D dataset?

### ISSUE THREAD

**Issue by Weah123** [ilucasgoncalves/AuxFormer#6]
How to preprocess the CREMA-D dataset? How to obtain the "label_consensus_1.csv"?

**Comment by youcaiSUN** [comment]
Also curious about the pre-processing of these label files.  Could you explain how to obtain them? I could not find them in the official CREAM-D github repo.

**Comment by ilucasgoncalves** [comment]
@youcaiSUN @Weah123 As mentioned in the CREMA-D repo 95% of the clips have more than 7 ratings. They provide a .csv file with the ratings provided by each annotator for each clip present in the dataset. If you take all the ratings and aggregate the annotations for each clip you can get the label consensus for the annotations. 

Here's an example:
Say we have clip 1001_ANG_XX.flv  and we have 5 workers annotating. Worker1=Happy, Worker2=Neutral, Worker3=Neutral, Worker4=Happy, Worker5=Happy.

if you aggregate these annotations and divide each emotional total by the global total you can get the consensus distribution for this file. 3 - Happy, 2 - Neutral, Total - 5

so the consensus for 1001_ANG_XX.flv is: 
Anger=0, Disgust=0, Fear=0, Happy=0.6, Neutral=0.4, Sad=0
